# Generated by Django 5.2.4 on 2026-07-08 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='max_members',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='min_members',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='DurationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('minutes', models.PositiveBigIntegerField()),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration_options', to='core.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('custom_sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('team_members', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.eventcategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subcategory')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.durationoption')),
            ],
        ),
    ]
