# Generated by Django 5.2.4 on 2026-07-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subcategory_max_members_subcategory_min_members_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'ordering': ['id']},
        ),
    ]
