# Generated by Django 5.2.4 on 2026-07-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_eventcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
