# Generated by Django 5.2.4 on 2026-07-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeContent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
