# Generated by Django 5.2.4 on 2026-07-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeContent', '0002_alter_teammember_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
